"""Is it work?

Revision ID: ddd19d43c0f6
Revises: 3ed9ead47859
Create Date: 2023-04-03 18:24:35.281204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddd19d43c0f6'
down_revision = '3ed9ead47859'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
